services:
  - type: web
    name: pipelineflow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://pipelineflow.vercel.app,http://localhost:3000 